version: '3.1'
services:
  mysql:
    environment:
      - MYSQL_DATABASE=tagprints
      - MYSQL_USER=tagprints
      - MYSQL_PASS=tagprints
    image: 'tutum/mysql:latest'
    volumes:
      - 'db_data:/var/lib/mysql'
  web:
    image: 'wordpress:latest'
    environment:
      - WORDPRESS_DB_NAME=tagprints
      - WORDPRESS_DB_USER=tagprints
      - WORDPRESS_DB_PASSWORD=tagprints
      - WORDPRESS_DEBUG="true"
      - APP_URL="//tagprints.com"
    volumes:
      - '/vagrant/wp-content/plugins:/var/www/html/wp-content/plugins'
      - >-
        /vagrant/wp-content/themes/tagprints-2018:/var/www/html/wp-content/themes/tagprints-2018
      - '/vagrant/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
    ports:
      - '80:80'
    links:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '10001:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: G3TIbvjNhbzb
volumes:
  db_data: null
