<?php
/**
 * @global GV_Import_Entries_Addon $this
 */
$form_title = $this->get_current_form_title();

?>

<div class="three-col">
	<div>
		<i class="dashicons dashicons-media-spreadsheet gv-import-icon"></i>
	</div>
	<div>
		<i class="dashicons dashicons-migrate gv-import-icon"></i>
	</div>
	<div>
		<?php if( is_callable(array('GFForms', 'get_admin_icon_b64' ))) { ?>
		<div class="wp-menu-image svg gv-import-icon" style="background-image: url('<?php echo GFForms::get_admin_icon_b64( '#464b50' ); ?>')!important;"></div>
		<?php } else {?>
		<i class="dashicons dashicons-list-view gv-import-icon"></i>
		<?php }	?>
	</div>
</div>

<?php

echo wpautop( sprintf( esc_html__('You&rsquo;re about to move data from the uploaded file to the Gravity Forms form "%s". If you have any questions about how to format the data  in your file upload, please read the %sFormatting Guide%s.

If using a file generated by Gravity Forms, you won&rsquo;t need to modify anything.', 'gravityview-importer' ), esc_html( $form_title ), '<a href="http://docs.gravityview.co/article/257-csv-import-gravity-forms-format">', '</a>' ) );

?>

<div class="hr-divider"></div>