version: '3.1'
services:
  proxy:
    image: 'steveltn/https-portal:1'
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    volumes:
      - './uploads.conf:/etc/nginx/conf.d/uploads.conf'
    environment:
      STAGE: production
      DOMAINS: 'admin.tagprints.com -> http://web'
  backup:
    image: 'tutum/dockup:latest'
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      BACKUP_NAME: tagprints-backup
      PATHS_TO_BACKUP: /var/lib/mysql
      RESTORE: 'false'
      S3_BUCKET_NAME: tagprints-backup
    volumes:
      - 'data:/var/lib/mysql'
  restore:
    image: 'tutum/dockup:latest'
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      BACKUP_NAME: tagprints-backup
      PATHS_TO_BACKUP: /var/lib/mysql
      RESTORE: 'true'
      S3_BUCKET_NAME: tagprints-backup
    volumes:
      - 'data:/var/lib/mysql'
  mysql:
    environment:
      MYSQL_DATABASE: '${WORDPRESS_DB_NAME}'
      MYSQL_USER: '${WORDPRESS_DB_USER}'
      MYSQL_PASS: '${WORDPRESS_DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
    image: 'tutum/mysql:latest'
    volumes:
      - 'data:/var/lib/mysql'
  web:
    image: 'maxbaun/tagprints-wordpress:latest'
    environment:
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_NAME}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASS}'
      APP_URL: //tagprints.com
    links:
      - mysql
    working_dir: /var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '10001:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
volumes:
  data: null
  uploads: null
