version: '3.1'
services:
  proxy:
    image: 'steveltn/https-portal:1'
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    volumes:
      - './uploads.conf:/etc/nginx/conf.d/uploads.conf'
    environment:
      STAGE: production
      DOMAINS: 'admin.tagprints.com -> http://web'
  backup:
    image: 'tutum/dockup:latest'
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIGPCJ6Q2CXMUH5JQ
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=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
      - BACKUP_NAME=tagprints-backup
      - PATHS_TO_BACKUP=/var/lib/mysql
      - RESTORE=false
      - S3_BUCKET_NAME=tagprints-backup
    volumes:
      - 'data:/var/lib/mysql'
  restore:
    image: 'tutum/dockup:latest'
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIGPCJ6Q2CXMUH5JQ
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=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
      - BACKUP_NAME=tagprints-backup
      - PATHS_TO_BACKUP=/var/lib/mysql
      - RESTORE=true
      - S3_BUCKET_NAME=tagprints-backup
    volumes:
      - 'data:/var/lib/mysql'
  mysql:
    environment:
      MYSQL_DATABASE: tagprints
      MYSQL_USER: tagprints
      MYSQL_PASS: rxBj34Zg6rYvhcWc
      MYSQL_ROOT_PASSWORD: T5aWNAaY2Dyttbzy
    image: 'tutum/mysql:latest'
    volumes:
      - 'data:/var/lib/mysql'
  web:
    image: 'maxbaun/tagprints-wordpress:latest'
    environment:
      - WORDPRESS_DB_NAME=tagprints
      - WORDPRESS_DB_USER=tagprints
      - WORDPRESS_DB_PASSWORD=rxBj34Zg6rYvhcWc
    links:
      - mysql
    working_dir: /var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '10001:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: T5aWNAaY2Dyttbzy
volumes:
  data: null
